/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface calculationEntity {
  'id'?: number;
}
export interface calculationdistributorEntity {
  'calculation_id': number;
  'distributor_id': number;
  'id'?: number;
  'rank': number;
}
export interface calculationitempartlistEntity {
  'calculation_id': number;
  'count': number;
  'id'?: number;
  'partlist_id': number;
  'rank': number;
}
export interface calculationrunEntity {
  'calculation_id': number;
  'date': Date;
  'id'?: number;
}
export interface calculationrunitemEntity {
  'calculationrun_id'?: number | null;
  'calculationrunitemtype_id': number;
  'count'?: number | null;
  'currency'?: string | null;
  'distributor_id'?: number | null;
  'id'?: number;
  'ordercode'?: string | null;
  'part_id'?: number | null;
  'price'?: number | null;
  'rank': number;
  'sum'?: number | null;
  'text': string;
}
export interface calculationrunitemtypeEntity {
  'id'?: number;
  'name': string;
}
export interface currencyEntity {
  'id'?: number;
  'in_eur': number;
  'name': string;
  'symbol': string;
}
export interface distributionEntity {
  'distributor_id'?: number | null;
  'id'?: number;
  'ordercode'?: string | null;
  'source_id'?: number | null;
}
export interface distribution_propertyEntity {
  'distribution_id': number;
  'id'?: number;
  'property': string;
  'value': string;
}
export interface distributorEntity {
  'id'?: number;
  'name': string;
}
export interface kicadEntity {
  'footprint'?: string | null;
  'id'?: number;
  'partid'?: number | null;
  'src_lib'?: string | null;
  'src_part'?: string | null;
  'target_lib'?: string | null;
}
export interface kicad_projectsEntity {
  'designname'?: string | null;
  'gitrepo'?: string | null;
  'id'?: number;
  'name'?: string | null;
  'path'?: string | null;
}
export interface manufacturerEntity {
  'id'?: number;
  'name'?: string | null;
}
export interface partEntity {
  'id'?: number;
  'name': string;
  'partclass'?: number | null;
  'prop01'?: string | null;
  'prop02'?: string | null;
  'prop03'?: string | null;
  'prop04'?: string | null;
  'prop05'?: string | null;
  'prop06'?: string | null;
  'prop07'?: string | null;
  'prop08'?: string | null;
  'prop09'?: string | null;
  'prop10'?: string | null;
  'prop11'?: string | null;
  'prop12'?: string | null;
  'prop13'?: string | null;
  'prop14'?: string | null;
  'prop15'?: string | null;
  'prop16'?: string | null;
}
export interface partclassEntity {
  'id'?: number;
  'name'?: string | null;
  'prop01'?: string | null;
  'prop02'?: string | null;
  'prop03'?: string | null;
  'prop04'?: string | null;
  'prop05'?: string | null;
  'prop06'?: string | null;
  'prop07'?: string | null;
  'prop08'?: string | null;
  'prop09'?: string | null;
  'prop10'?: string | null;
  'prop11'?: string | null;
  'prop12'?: string | null;
  'prop13'?: string | null;
  'prop14'?: string | null;
  'prop15'?: string | null;
  'prop16'?: string | null;
}
export interface partlistEntity {
  'date'?: Date | null;
  'id'?: number;
  'name'?: string | null;
  'sourcefile'?: string | null;
  'version'?: string | null;
}
export interface partlistitemEntity {
  'count'?: number | null;
  'id'?: number;
  'part_id'?: number | null;
  'partlist_id'?: number | null;
  'rank'?: number | null;
  'value'?: string | null;
}
export interface priceEntity {
  'currency': number;
  'distribution_id': number;
  'id'?: number;
  'min': number;
  'mult': number;
  'value': number;
}
export interface priceineurEntity {
  'distribution_id': number;
  'id'?: number;
  'min': number;
  'mult': number;
  'value'?: number;
}
export interface sourceEntity {
  'id'?: number;
  'manufacturer_id'?: number | null;
  'ordercode'?: string | null;
  'part_id'?: number | null;
}
export interface event_dataEntity {
  'data_id'?: number;
  'hash'?: string | null;
  'shared_data'?: string | null;
}
export interface event_typesEntity {
  'event_type'?: string | null;
  'event_type_id'?: number;
}
export interface eventsEntity {
  'context_id'?: string | null;
  'context_id_bin'?: any | null;
  'context_parent_id'?: string | null;
  'context_parent_id_bin'?: any | null;
  'context_user_id'?: string | null;
  'context_user_id_bin'?: any | null;
  'data_id'?: number | null;
  'event_data'?: string | null;
  'event_id'?: number;
  'event_type'?: string | null;
  'event_type_id'?: number | null;
  'origin'?: string | null;
  'origin_idx'?: number | null;
  'time_fired'?: Date | null;
  'time_fired_ts'?: number | null;
}
export interface recorder_runsEntity {
  'closed_incorrect'?: number | null;
  'created'?: Date | null;
  'end'?: Date | null;
  'run_id'?: number;
  'start'?: Date | null;
}
export interface schema_changesEntity {
  'change_id'?: number;
  'changed'?: Date | null;
  'schema_version'?: number | null;
}
export interface state_attributesEntity {
  'attributes_id'?: number;
  'hash'?: string | null;
  'shared_attrs'?: string | null;
}
export interface statesEntity {
  'attributes'?: string | null;
  'attributes_id'?: number | null;
  'context_id'?: string | null;
  'context_id_bin'?: any | null;
  'context_parent_id'?: string | null;
  'context_parent_id_bin'?: any | null;
  'context_user_id'?: string | null;
  'context_user_id_bin'?: any | null;
  'entity_id'?: string | null;
  'event_id'?: number | null;
  'last_changed'?: Date | null;
  'last_changed_ts'?: number | null;
  'last_updated'?: Date | null;
  'last_updated_ts'?: number | null;
  'metadata_id'?: number | null;
  'old_state_id'?: number | null;
  'origin_idx'?: number | null;
  'state'?: string | null;
  'state_id'?: number;
}
export interface states_metaEntity {
  'entity_id'?: string | null;
  'metadata_id'?: number;
}
export interface statisticsEntity {
  'created'?: Date | null;
  'created_ts'?: number | null;
  'id'?: number;
  'last_reset'?: Date | null;
  'last_reset_ts'?: number | null;
  'max'?: number | null;
  'mean'?: number | null;
  'metadata_id'?: number | null;
  'min'?: number | null;
  'start'?: Date | null;
  'start_ts'?: number | null;
  'state'?: number | null;
  'sum'?: number | null;
}
export interface statistics_metaEntity {
  'has_mean'?: number | null;
  'has_sum'?: number | null;
  'id'?: number;
  'name'?: string | null;
  'source'?: string | null;
  'statistic_id'?: string | null;
  'unit_of_measurement'?: string | null;
}
export interface statistics_runsEntity {
  'run_id'?: number;
  'start'?: Date | null;
}
export interface statistics_short_termEntity {
  'created'?: Date | null;
  'created_ts'?: number | null;
  'id'?: number;
  'last_reset'?: Date | null;
  'last_reset_ts'?: number | null;
  'max'?: number | null;
  'mean'?: number | null;
  'metadata_id'?: number | null;
  'min'?: number | null;
  'start'?: Date | null;
  'start_ts'?: number | null;
  'state'?: number | null;
  'sum'?: number | null;
}
export interface transactionEntity {
  'commissionValue': string;
  'currency'?: string | null;
  'cycle': number;
  'date': Date;
  'executionDay': number;
  'fees': string;
  'id'?: number;
  'localAccountNumber': string;
  'localBankCode': string;
  'new'?: number;
  'purpose': string;
  'remoteAccountNumber'?: string | null;
  'remoteBankCode'?: string | null;
  'remoteBic'?: string | null;
  'remoteIban'?: string | null;
  'remoteName'?: string | null;
  'transactionCode': number;
  'transactionKey': string;
  'transactionText'?: string | null;
  'type': string;
  'unitPriceValue': string;
  'units': string;
  'value': number;
  'valutaDate': Date;
}
