/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface calculationEntity {
  'id'?: number;
}
export interface calculationdistributorEntity {
  'calculation_id': number;
  'distributor_id': number;
  'id'?: number;
  'rank': number;
}
export interface calculationitempartlistEntity {
  'calculation_id': number;
  'count': number;
  'id'?: number;
  'partlist_id': number;
  'rank': number;
}
export interface calculationrunEntity {
  'calculation_id': number;
  'date': Date;
  'id'?: number;
}
export interface calculationrunitemEntity {
  'calculationrun_id'?: number | null;
  'calculationrunitemtype_id': number;
  'count'?: number | null;
  'currency'?: string | null;
  'distributor_id'?: number | null;
  'id'?: number;
  'ordercode'?: string | null;
  'part_id'?: number | null;
  'price'?: number | null;
  'rank': number;
  'sum'?: number | null;
  'text': string;
}
export interface calculationrunitemtypeEntity {
  'id'?: number;
  'name': string;
}
export interface currencyEntity {
  'id'?: number;
  'in_eur': number;
  'name': string;
  'symbol': string;
}
export interface distributionEntity {
  'distributor_id'?: number | null;
  'id'?: number;
  'ordercode'?: string | null;
  'source_id'?: number | null;
}
export interface distributorEntity {
  'id'?: number;
  'name': string;
}
export interface kicadEntity {
  'footprint'?: string | null;
  'id'?: number;
  'partid'?: number | null;
  'src_lib'?: string | null;
  'src_part'?: string | null;
  'target_lib'?: string | null;
}
export interface manufacturerEntity {
  'id'?: number;
  'name'?: string | null;
}
export interface partEntity {
  'id'?: number;
  'name': string;
  'partclass'?: number | null;
  'prop01'?: string | null;
  'prop02'?: string | null;
  'prop03'?: string | null;
  'prop04'?: string | null;
  'prop05'?: string | null;
  'prop06'?: string | null;
  'prop07'?: string | null;
  'prop08'?: string | null;
  'prop09'?: string | null;
  'prop10'?: string | null;
  'prop11'?: string | null;
  'prop12'?: string | null;
  'prop13'?: string | null;
  'prop14'?: string | null;
  'prop15'?: string | null;
  'prop16'?: string | null;
}
export interface partclassEntity {
  'id'?: number;
  'name'?: string | null;
  'prop01'?: string | null;
  'prop02'?: string | null;
  'prop03'?: string | null;
  'prop04'?: string | null;
  'prop05'?: string | null;
  'prop06'?: string | null;
  'prop07'?: string | null;
  'prop08'?: string | null;
  'prop09'?: string | null;
  'prop10'?: string | null;
  'prop11'?: string | null;
  'prop12'?: string | null;
  'prop13'?: string | null;
  'prop14'?: string | null;
  'prop15'?: string | null;
  'prop16'?: string | null;
}
export interface partlistEntity {
  'date'?: Date | null;
  'id'?: number;
  'name'?: string | null;
  'sourcefile'?: string | null;
}
export interface partlistitemEntity {
  'count'?: number | null;
  'id'?: number;
  'part_id'?: number | null;
  'partlist_id'?: number | null;
  'rank'?: number | null;
  'value'?: string | null;
}
export interface priceEntity {
  'currency': number;
  'distribution_id': number;
  'id'?: number;
  'min': number;
  'mult': number;
  'value': number;
}
export interface priceineurEntity {
  'distribution_id': number;
  'id'?: number;
  'min': number;
  'mult': number;
  'value'?: number;
}
export interface sourceEntity {
  'id'?: number;
  'manufacturer_id'?: number | null;
  'ordercode'?: string | null;
  'part_id'?: number | null;
}
export interface transactionEntity {
  'commissionValue': string;
  'currency'?: string | null;
  'cycle': number;
  'date': Date;
  'executionDay': number;
  'fees': string;
  'id'?: number;
  'localAccountNumber': string;
  'localBankCode': string;
  'new'?: number;
  'purpose': string;
  'remoteAccountNumber'?: string | null;
  'remoteBankCode'?: string | null;
  'remoteBic'?: string | null;
  'remoteIban'?: string | null;
  'remoteName'?: string | null;
  'transactionCode': number;
  'transactionKey': string;
  'transactionText'?: string | null;
  'type': string;
  'unitPriceValue': string;
  'units': string;
  'value': number;
  'valutaDate': Date;
}
